apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels: 
    app: mong-express
spec:
  selector:
    matchLabels:
      app: mong-express
  template:
    metadata:
      labels:
        app: mong-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodbsecrets
              key: mongo-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodbsecrets
              key: mongo-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: express-configmap
              key: database_name
---
apiVersion: v1
kind: Service
metadata:
  name: mong-express
spec:
  selector:
    app: mong-express
  ports: 
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer